- hosts: localhost
  
  tasks:
  - name: Login
    include_tasks: ../login.yml

  - name: Create CU config map
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../..//templates/config/gnb_cu.yaml') | from_yaml }}"
  
  - name: Deploy CU
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../..//templates/deployment/gnb_cu.yaml') | from_yaml }}"

  - name: Create CU service
    kubernetes.core.k8s:
        api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
        state: present
        definition: "{{ lookup('template', '../../templates/service/gnb_cu.yaml') | from_yaml }}"
