apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
   name: gnb
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata: 
  name: gnb
spec: 
  output: 
    to: 
      kind: ImageStreamTag
      name: "gnb:develop"
  runPolicy: Serial
  strategy:
    type: Docker
  source: 
    dockerfile: |
        FROM image-registry.openshift-image-registry.svc:5000/ran-build:develop AS gnb-build

        # Now we are copying from builder-image
        COPY --from=gnb-base /usr/local/bin/uhd_find_devices /usr/local/bin
        COPY --from=gnb-base /usr/local/lib64/uhd/utils/uhd_images_downloader.py /opt/gnb/bin

        WORKDIR /usr/local/share/uhd/rfnoc
        COPY --from=gnb-base /usr/local/share/uhd/rfnoc/ .

        RUN /bin/bash -c "ln -s /usr/local/lib/lib_usrpdevif.so /usr/local/lib/lib_device.so" && \
            ldconfig

        # Copy the relevant configuration files for gNB
        WORKDIR /opt/gnb/etc
        COPY --from=gnb-build /ran/docker/etc