apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
   name: upf
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "upf"
spec:
    runPolicy: "Serial"
    source:
        git:
            uri: "https://github.com/openRAN/upf.git"
            ref: "v1.4.0"
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
        configMaps:
          - configMap:
              name: rhsm-conf
            destinationDir: rhsm-conf
          - configMap:
              name: rhsm-ca
            destinationDir: rhsm-ca
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.upf"
    output:
        to:
            kind: "ImageStreamTag"
            name: "upf:v1.4.0"

